# Generated by Django 4.2.25 on 2025-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesser', '0002_characters_alter_answer_id_alter_gamesession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='Occupation',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='characters',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
