# Generated by Django 4.2.25 on 2025-12-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guesser', '0003_characters_occupation_alter_characters_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='characters',
        ),
    ]
